// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Source struct {
	SourceType SourceType `json:"sourceType"`
	// source datasource version information
	Version string `json:"version"`
}

const SourceAvroCRC64Fingerprint = "\xf0>U\x15,f\xc6E"

func NewSource() Source {
	r := Source{}
	return r
}

func DeserializeSource(r io.Reader) (Source, error) {
	t := NewSource()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeSourceFromSchema(r io.Reader, schema string) (Source, error) {
	t := NewSource()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeSource(r Source, w io.Writer) error {
	var err error
	err = writeSourceType(r.SourceType, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Version, w)
	if err != nil {
		return err
	}
	return err
}

func (r Source) Serialize(w io.Writer) error {
	return writeSource(r, w)
}

func (r Source) Schema() string {
	return "{\"fields\":[{\"name\":\"sourceType\",\"type\":{\"name\":\"SourceType\",\"namespace\":\"com.bytedance.dts.subscribe.avro\",\"symbols\":[\"MySQL\",\"Oracle\",\"SQLServer\",\"PostgreSQL\",\"MongoDB\",\"Redis\",\"DB2\",\"PPAS\",\"DRDS\",\"HBASE\",\"HDFS\",\"FILE\",\"OTHER\"],\"type\":\"enum\"}},{\"doc\":\"source datasource version information\",\"name\":\"version\",\"type\":\"string\"}],\"name\":\"com.bytedance.dts.subscribe.avro.Source\",\"type\":\"record\"}"
}

func (r Source) SchemaName() string {
	return "com.bytedance.dts.subscribe.avro.Source"
}

func (_ Source) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Source) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Source) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Source) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Source) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Source) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Source) SetString(v string)   { panic("Unsupported operation") }
func (_ Source) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Source) Get(i int) types.Field {
	switch i {
	case 0:
		w := SourceTypeWrapper{Target: &r.SourceType}

		return w

	case 1:
		w := types.String{Target: &r.Version}

		return w

	}
	panic("Unknown field index")
}

func (r *Source) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Source) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Source) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Source) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Source) HintSize(int)                     { panic("Unsupported operation") }
func (_ Source) Finalize()                        {}

func (_ Source) AvroCRC64Fingerprint() []byte {
	return []byte(SourceAvroCRC64Fingerprint)
}

func (r Source) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["sourceType"], err = json.Marshal(r.SourceType)
	if err != nil {
		return nil, err
	}
	output["version"], err = json.Marshal(r.Version)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Source) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["sourceType"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.SourceType); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for sourceType")
	}
	val = func() json.RawMessage {
		if v, ok := fields["version"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Version); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for version")
	}
	return nil
}
