// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
/*
 * SOURCE:
 *     record.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type TimestampWithTimeZone struct {
	Value DateTime `json:"value"`

	Timezone string `json:"timezone"`
}

const TimestampWithTimeZoneAvroCRC64Fingerprint = "l\x0f\x14\x9fV\xba\x9b\xcf"

func NewTimestampWithTimeZone() TimestampWithTimeZone {
	r := TimestampWithTimeZone{}
	r.Value = NewDateTime()

	return r
}

func DeserializeTimestampWithTimeZone(r io.Reader) (TimestampWithTimeZone, error) {
	t := NewTimestampWithTimeZone()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeTimestampWithTimeZoneFromSchema(r io.Reader, schema string) (TimestampWithTimeZone, error) {
	t := NewTimestampWithTimeZone()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeTimestampWithTimeZone(r TimestampWithTimeZone, w io.Writer) error {
	var err error
	err = writeDateTime(r.Value, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Timezone, w)
	if err != nil {
		return err
	}
	return err
}

func (r TimestampWithTimeZone) Serialize(w io.Writer) error {
	return writeTimestampWithTimeZone(r, w)
}

func (r TimestampWithTimeZone) Schema() string {
	return "{\"fields\":[{\"name\":\"value\",\"type\":{\"fields\":[{\"default\":null,\"name\":\"year\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"month\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"day\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"hour\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"minute\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"second\",\"type\":[\"null\",\"int\"]},{\"default\":null,\"name\":\"millis\",\"type\":[\"null\",\"int\"]}],\"name\":\"DateTime\",\"namespace\":\"com.bytedance.dts.subscribe.avro\",\"type\":\"record\"}},{\"name\":\"timezone\",\"type\":\"string\"}],\"name\":\"com.bytedance.dts.subscribe.avro.TimestampWithTimeZone\",\"type\":\"record\"}"
}

func (r TimestampWithTimeZone) SchemaName() string {
	return "com.bytedance.dts.subscribe.avro.TimestampWithTimeZone"
}

func (_ TimestampWithTimeZone) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetInt(v int32)       { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetLong(v int64)      { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetString(v string)   { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *TimestampWithTimeZone) Get(i int) types.Field {
	switch i {
	case 0:
		r.Value = NewDateTime()

		w := types.Record{Target: &r.Value}

		return w

	case 1:
		w := types.String{Target: &r.Timezone}

		return w

	}
	panic("Unknown field index")
}

func (r *TimestampWithTimeZone) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *TimestampWithTimeZone) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ TimestampWithTimeZone) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) HintSize(int)                     { panic("Unsupported operation") }
func (_ TimestampWithTimeZone) Finalize()                        {}

func (_ TimestampWithTimeZone) AvroCRC64Fingerprint() []byte {
	return []byte(TimestampWithTimeZoneAvroCRC64Fingerprint)
}

func (r TimestampWithTimeZone) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["value"], err = json.Marshal(r.Value)
	if err != nil {
		return nil, err
	}
	output["timezone"], err = json.Marshal(r.Timezone)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *TimestampWithTimeZone) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["value"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Value); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for value")
	}
	val = func() json.RawMessage {
		if v, ok := fields["timezone"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Timezone); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for timezone")
	}
	return nil
}
