// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1-devel
// 	protoc        v3.19.4
// source: volcengine/vod/business/vod_edit.proto

package business

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitDirectEditTaskAsyncResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId string `protobuf:"bytes,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"` // 视频编辑执行Id
}

func (x *SubmitDirectEditTaskAsyncResult) Reset() {
	*x = SubmitDirectEditTaskAsyncResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitDirectEditTaskAsyncResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDirectEditTaskAsyncResult) ProtoMessage() {}

func (x *SubmitDirectEditTaskAsyncResult) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDirectEditTaskAsyncResult.ProtoReflect.Descriptor instead.
func (*SubmitDirectEditTaskAsyncResult) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitDirectEditTaskAsyncResult) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

type GetDirectEditProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *GetDirectEditProgress) Reset() {
	*x = GetDirectEditProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectEditProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectEditProgress) ProtoMessage() {}

func (x *GetDirectEditProgress) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectEditProgress.ProtoReflect.Descriptor instead.
func (*GetDirectEditProgress) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{1}
}

func (x *GetDirectEditProgress) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type GetDirectEditResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqId        string     `protobuf:"bytes,1,opt,name=ReqId,proto3" json:"ReqId,omitempty"`               // 视频编辑执行Id
	EditParam    *EditParam `protobuf:"bytes,2,opt,name=EditParam,proto3" json:"EditParam,omitempty"`       // 视频编辑参数
	Priority     int32      `protobuf:"varint,3,opt,name=Priority,proto3" json:"Priority,omitempty"`        // 优先级
	CallbackUri  string     `protobuf:"bytes,4,opt,name=CallbackUri,proto3" json:"CallbackUri,omitempty"`   // 回调地址
	CallbackArgs string     `protobuf:"bytes,5,opt,name=CallbackArgs,proto3" json:"CallbackArgs,omitempty"` // 回调参数
	Status       string     `protobuf:"bytes,6,opt,name=Status,proto3" json:"Status,omitempty"`             // 编辑任务状态
	OutputVid    string     `protobuf:"bytes,7,opt,name=OutputVid,proto3" json:"OutputVid,omitempty"`       // 产物vid
}

func (x *GetDirectEditResult) Reset() {
	*x = GetDirectEditResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDirectEditResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectEditResult) ProtoMessage() {}

func (x *GetDirectEditResult) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectEditResult.ProtoReflect.Descriptor instead.
func (*GetDirectEditResult) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{2}
}

func (x *GetDirectEditResult) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *GetDirectEditResult) GetEditParam() *EditParam {
	if x != nil {
		return x.EditParam
	}
	return nil
}

func (x *GetDirectEditResult) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *GetDirectEditResult) GetCallbackUri() string {
	if x != nil {
		return x.CallbackUri
	}
	return ""
}

func (x *GetDirectEditResult) GetCallbackArgs() string {
	if x != nil {
		return x.CallbackArgs
	}
	return ""
}

func (x *GetDirectEditResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDirectEditResult) GetOutputVid() string {
	if x != nil {
		return x.OutputVid
	}
	return ""
}

type EditParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Canvas   *Canvas           `protobuf:"bytes,1,opt,name=Canvas,proto3" json:"Canvas,omitempty"`
	Output   *Output           `protobuf:"bytes,2,opt,name=Output,proto3" json:"Output,omitempty"`
	Track    []*structpb.Value `protobuf:"bytes,3,rep,name=Track,proto3" json:"Track,omitempty"`
	Upload   *Upload           `protobuf:"bytes,4,opt,name=Upload,proto3" json:"Upload,omitempty"`
	Uploader string            `protobuf:"bytes,5,opt,name=Uploader,proto3" json:"Uploader,omitempty"`
}

func (x *EditParam) Reset() {
	*x = EditParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditParam) ProtoMessage() {}

func (x *EditParam) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditParam.ProtoReflect.Descriptor instead.
func (*EditParam) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{3}
}

func (x *EditParam) GetCanvas() *Canvas {
	if x != nil {
		return x.Canvas
	}
	return nil
}

func (x *EditParam) GetOutput() *Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *EditParam) GetTrack() []*structpb.Value {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *EditParam) GetUpload() *Upload {
	if x != nil {
		return x.Upload
	}
	return nil
}

func (x *EditParam) GetUploader() string {
	if x != nil {
		return x.Uploader
	}
	return ""
}

type Canvas struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=Width,proto3" json:"Width,omitempty"`
}

func (x *Canvas) Reset() {
	*x = Canvas{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canvas) ProtoMessage() {}

func (x *Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Canvas.ProtoReflect.Descriptor instead.
func (*Canvas) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{4}
}

func (x *Canvas) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Canvas) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alpha        bool   `protobuf:"varint,1,opt,name=Alpha,proto3" json:"Alpha,omitempty"`
	Codec        *Codec `protobuf:"bytes,2,opt,name=Codec,proto3" json:"Codec,omitempty"`
	DisableAudio bool   `protobuf:"varint,3,opt,name=DisableAudio,proto3" json:"DisableAudio,omitempty"`
	DisableVideo bool   `protobuf:"varint,4,opt,name=DisableVideo,proto3" json:"DisableVideo,omitempty"`
	Fps          int32  `protobuf:"varint,5,opt,name=Fps,proto3" json:"Fps,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{5}
}

func (x *Output) GetAlpha() bool {
	if x != nil {
		return x.Alpha
	}
	return false
}

func (x *Output) GetCodec() *Codec {
	if x != nil {
		return x.Codec
	}
	return nil
}

func (x *Output) GetDisableAudio() bool {
	if x != nil {
		return x.DisableAudio
	}
	return false
}

func (x *Output) GetDisableVideo() bool {
	if x != nil {
		return x.DisableVideo
	}
	return false
}

func (x *Output) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type Codec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AudioBitrate int32  `protobuf:"varint,1,opt,name=AudioBitrate,proto3" json:"AudioBitrate,omitempty"`
	AudioCodec   string `protobuf:"bytes,2,opt,name=AudioCodec,proto3" json:"AudioCodec,omitempty"`
	Crf          int32  `protobuf:"varint,3,opt,name=Crf,proto3" json:"Crf,omitempty"`
	Preset       string `protobuf:"bytes,4,opt,name=Preset,proto3" json:"Preset,omitempty"`
	VideoCodec   string `protobuf:"bytes,5,opt,name=VideoCodec,proto3" json:"VideoCodec,omitempty"`
}

func (x *Codec) Reset() {
	*x = Codec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Codec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Codec) ProtoMessage() {}

func (x *Codec) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Codec.ProtoReflect.Descriptor instead.
func (*Codec) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{6}
}

func (x *Codec) GetAudioBitrate() int32 {
	if x != nil {
		return x.AudioBitrate
	}
	return 0
}

func (x *Codec) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *Codec) GetCrf() int32 {
	if x != nil {
		return x.Crf
	}
	return 0
}

func (x *Codec) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *Codec) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

type Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         string  `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Source     string  `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	TargetTime []int32 `protobuf:"varint,3,rep,packed,name=TargetTime,proto3" json:"TargetTime,omitempty"`
	Type       string  `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *Track) Reset() {
	*x = Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{7}
}

func (x *Track) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Track) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Track) GetTargetTime() []int32 {
	if x != nil {
		return x.TargetTime
	}
	return nil
}

func (x *Track) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Upload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SpaceName string `protobuf:"bytes,1,opt,name=SpaceName,proto3" json:"SpaceName,omitempty"`
	VideoName string `protobuf:"bytes,2,opt,name=VideoName,proto3" json:"VideoName,omitempty"`
}

func (x *Upload) Reset() {
	*x = Upload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Upload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upload) ProtoMessage() {}

func (x *Upload) ProtoReflect() protoreflect.Message {
	mi := &file_volcengine_vod_business_vod_edit_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upload.ProtoReflect.Descriptor instead.
func (*Upload) Descriptor() ([]byte, []int) {
	return file_volcengine_vod_business_vod_edit_proto_rawDescGZIP(), []int{8}
}

func (x *Upload) GetSpaceName() string {
	if x != nil {
		return x.SpaceName
	}
	return ""
}

func (x *Upload) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

var File_volcengine_vod_business_vod_edit_proto protoreflect.FileDescriptor

var file_volcengine_vod_business_vod_edit_proto_rawDesc = []byte{
	0x0a, 0x26, 0x76, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x6f, 0x64,
	0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2f, 0x76, 0x6f, 0x64, 0x5f, 0x65, 0x64,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x56, 0x6f, 0x6c, 0x63, 0x65, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x1f, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x41, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x22,
	0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x45, 0x64, 0x69, 0x74,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x8c, 0x02, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x45, 0x64,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x71, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x71, 0x49, 0x64, 0x12, 0x47,
	0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x56, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56,
	0x6f, 0x64, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x09, 0x45, 0x64,
	0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55,
	0x72, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61,
	0x63, 0x6b, 0x55, 0x72, 0x69, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x41, 0x72, 0x67, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x43, 0x61, 0x6c,
	0x6c, 0x62, 0x61, 0x63, 0x6b, 0x41, 0x72, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x56, 0x69, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x56, 0x69, 0x64, 0x22,
	0x95, 0x02, 0x0a, 0x09, 0x45, 0x64, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x3e, 0x0a,
	0x06, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x56, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x43,
	0x61, 0x6e, 0x76, 0x61, 0x73, 0x52, 0x06, 0x43, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x12, 0x3e, 0x0a,
	0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e,
	0x56, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x2c, 0x0a,
	0x05, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x06, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x56, 0x6f,
	0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x6f, 0x64, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x52, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x76, 0x61,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x22,
	0xb5, 0x01, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x6c,
	0x70, 0x68, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x41, 0x6c, 0x70, 0x68, 0x61,
	0x12, 0x3b, 0x0a, 0x05, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x56, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x56, 0x6f, 0x64,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x52, 0x05, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x22, 0x0a,
	0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x75, 0x64, 0x69,
	0x6f, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x46, 0x70, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x05, 0x43, 0x6f, 0x64, 0x65,
	0x63, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x69, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x42, 0x69,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x43, 0x6f,
	0x64, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x72, 0x66, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x43, 0x72, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x73, 0x65,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x72, 0x65, 0x73, 0x65, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x63, 0x22,
	0x63, 0x0a, 0x05, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x44, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x70, 0x61, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0xc8, 0x01, 0x0a, 0x29, 0x63,
	0x6f, 0x6d, 0x2e, 0x76, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x6f, 0x64, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x42, 0x07, 0x56, 0x6f, 0x64, 0x45, 0x64, 0x69,
	0x74, 0x50, 0x01, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x6f, 0x6c, 0x63, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2f, 0x76, 0x6f, 0x6c, 0x63, 0x2d,
	0x73, 0x64, 0x6b, 0x2d, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x76, 0x6f, 0x64, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0xa0, 0x01, 0x01, 0xd8, 0x01, 0x01, 0xca, 0x02, 0x20, 0x56,
	0x6f, 0x6c, 0x63, 0x5c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5c, 0x56, 0x6f, 0x64, 0x5c,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x5c, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0xe2,
	0x02, 0x23, 0x56, 0x6f, 0x6c, 0x63, 0x5c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5c, 0x56,
	0x6f, 0x64, 0x5c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_volcengine_vod_business_vod_edit_proto_rawDescOnce sync.Once
	file_volcengine_vod_business_vod_edit_proto_rawDescData = file_volcengine_vod_business_vod_edit_proto_rawDesc
)

func file_volcengine_vod_business_vod_edit_proto_rawDescGZIP() []byte {
	file_volcengine_vod_business_vod_edit_proto_rawDescOnce.Do(func() {
		file_volcengine_vod_business_vod_edit_proto_rawDescData = protoimpl.X.CompressGZIP(file_volcengine_vod_business_vod_edit_proto_rawDescData)
	})
	return file_volcengine_vod_business_vod_edit_proto_rawDescData
}

var file_volcengine_vod_business_vod_edit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_volcengine_vod_business_vod_edit_proto_goTypes = []interface{}{
	(*SubmitDirectEditTaskAsyncResult)(nil), // 0: Volcengine.Vod.Models.Business.SubmitDirectEditTaskAsyncResult
	(*GetDirectEditProgress)(nil),           // 1: Volcengine.Vod.Models.Business.GetDirectEditProgress
	(*GetDirectEditResult)(nil),             // 2: Volcengine.Vod.Models.Business.GetDirectEditResult
	(*EditParam)(nil),                       // 3: Volcengine.Vod.Models.Business.EditParam
	(*Canvas)(nil),                          // 4: Volcengine.Vod.Models.Business.Canvas
	(*Output)(nil),                          // 5: Volcengine.Vod.Models.Business.Output
	(*Codec)(nil),                           // 6: Volcengine.Vod.Models.Business.Codec
	(*Track)(nil),                           // 7: Volcengine.Vod.Models.Business.Track
	(*Upload)(nil),                          // 8: Volcengine.Vod.Models.Business.Upload
	(*structpb.Value)(nil),                  // 9: google.protobuf.Value
}
var file_volcengine_vod_business_vod_edit_proto_depIdxs = []int32{
	3, // 0: Volcengine.Vod.Models.Business.GetDirectEditResult.EditParam:type_name -> Volcengine.Vod.Models.Business.EditParam
	4, // 1: Volcengine.Vod.Models.Business.EditParam.Canvas:type_name -> Volcengine.Vod.Models.Business.Canvas
	5, // 2: Volcengine.Vod.Models.Business.EditParam.Output:type_name -> Volcengine.Vod.Models.Business.Output
	9, // 3: Volcengine.Vod.Models.Business.EditParam.Track:type_name -> google.protobuf.Value
	8, // 4: Volcengine.Vod.Models.Business.EditParam.Upload:type_name -> Volcengine.Vod.Models.Business.Upload
	6, // 5: Volcengine.Vod.Models.Business.Output.Codec:type_name -> Volcengine.Vod.Models.Business.Codec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_volcengine_vod_business_vod_edit_proto_init() }
func file_volcengine_vod_business_vod_edit_proto_init() {
	if File_volcengine_vod_business_vod_edit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_volcengine_vod_business_vod_edit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitDirectEditTaskAsyncResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectEditProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDirectEditResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Canvas); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Codec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_volcengine_vod_business_vod_edit_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Upload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_volcengine_vod_business_vod_edit_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_volcengine_vod_business_vod_edit_proto_goTypes,
		DependencyIndexes: file_volcengine_vod_business_vod_edit_proto_depIdxs,
		MessageInfos:      file_volcengine_vod_business_vod_edit_proto_msgTypes,
	}.Build()
	File_volcengine_vod_business_vod_edit_proto = out.File
	file_volcengine_vod_business_vod_edit_proto_rawDesc = nil
	file_volcengine_vod_business_vod_edit_proto_goTypes = nil
	file_volcengine_vod_business_vod_edit_proto_depIdxs = nil
}
